ALTER TABLE content ADD `title_pt` varchar(255) NOT NULL;
ALTER TABLE content ADD `content_pt` BLOB NOT NULL;
ALTER TABLE content CHANGE  `title_pt`  `title_pt` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ;

ALTER TABLE emails ADD `title_pt` varchar(255) NOT NULL;
ALTER TABLE emails ADD `content_pt` BLOB NOT NULL;
ALTER TABLE emails CHANGE  `title_pt`  `title_pt` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ;

ALTER TABLE lang ADD `pt` varchar(255) NOT NULL;
ALTER TABLE lang CHANGE `pt` `pt` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;

ALTER TABLE order_types ADD `name_pt` varchar(255) NOT NULL;
ALTER TABLE order_types CHANGE  `name_pt`  `name_pt` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ;

ALTER TABLE transaction_types ADD `name_pt` varchar(255) NOT NULL;
ALTER TABLE transaction_types CHANGE  `name_pt`  `name_pt` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ;

ALTER TABLE request_types ADD `name_pt` varchar(255) NOT NULL;
ALTER TABLE request_types CHANGE  `name_pt`  `name_pt` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ;

ALTER TABLE request_status ADD `name_pt` varchar(255) NOT NULL;
ALTER TABLE request_status CHANGE  `name_pt`  `name_pt` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ;

ALTER TABLE request_descriptions ADD `name_pt` varchar(255) NOT NULL;
ALTER TABLE request_descriptions CHANGE  `name_pt`  `name_pt` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ;

ALTER TABLE history_actions ADD `name_pt` varchar(255) NOT NULL;
ALTER TABLE history_actions CHANGE  `name_pt`  `name_pt` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ;

INSERT INTO `admin_controls_methods` (`id`, `method`, `arguments`, `order`, `control_id`, `p_id`) VALUES
(2839, 'textInput', 'a:13:{s:4:"name";s:7:"name_pt";s:7:"caption";s:9:"Name (PT)";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:0:"";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}', 2, 258, 0),
(2838, 'field', 'a:14:{s:4:"name";s:7:"name_pt";s:7:"caption";s:16:"Description (PT)";s:8:"subtable";s:0:"";s:15:"subtable_fields";s:0:"";s:8:"link_url";s:0:"";s:11:"concat_char";s:0:"";s:7:"in_form";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:14:"override_value";s:0:"";s:13:"link_id_field";s:0:"";}', 2, 230, 0),
(2837, 'textInput', 'a:13:{s:4:"name";s:7:"name_pt";s:7:"caption";s:16:"Description (PT)";s:8:"required";s:1:"1";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:0:"";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}', 2, 229, 0),
(2836, 'field', 'a:14:{s:4:"name";s:7:"name_pt";s:7:"caption";s:9:"Name (PT)";s:8:"subtable";s:0:"";s:15:"subtable_fields";s:0:"";s:8:"link_url";s:0:"";s:11:"concat_char";s:0:"";s:7:"in_form";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:14:"override_value";s:0:"";s:13:"link_id_field";s:0:"";}', 2, 227, 0),
(2835, 'textInput', 'a:13:{s:4:"name";s:7:"name_pt";s:7:"caption";s:9:"Name (PT)";s:8:"required";s:1:"1";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:0:"";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}', 2, 226, 0),
(2834, 'field', 'a:14:{s:4:"name";s:7:"name_pt";s:7:"caption";s:9:"Name (PT)";s:8:"subtable";s:0:"";s:15:"subtable_fields";s:0:"";s:8:"link_url";s:0:"";s:11:"concat_char";s:0:"";s:7:"in_form";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:14:"override_value";s:0:"";s:13:"link_id_field";s:0:"";}', 2, 223, 0),
(2833, 'textInput', 'a:13:{s:4:"name";s:7:"name_pt";s:7:"caption";s:9:"Name (PT)";s:8:"required";s:1:"1";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:0:"";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}', 2, 222, 0),
(2832, 'field', 'a:14:{s:4:"name";s:7:"name_pt";s:7:"caption";s:9:"Name (PT)";s:8:"subtable";s:0:"";s:15:"subtable_fields";s:0:"";s:8:"link_url";s:0:"";s:11:"concat_char";s:0:"";s:7:"in_form";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:14:"override_value";s:0:"";s:13:"link_id_field";s:0:"";}', 2, 220, 0),
(2831, 'textInput', 'a:13:{s:4:"name";s:7:"name_pt";s:7:"caption";s:9:"Name (PT)";s:8:"required";s:1:"1";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:0:"";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}', 2, 219, 0),
(2830, 'field', 'a:14:{s:4:"name";s:7:"name_pt";s:7:"caption";s:9:"Name (PT)";s:8:"subtable";s:0:"";s:15:"subtable_fields";s:0:"";s:8:"link_url";s:0:"";s:11:"concat_char";s:0:"";s:7:"in_form";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:14:"override_value";s:0:"";s:13:"link_id_field";s:0:"";}', 2, 212, 0),
(2829, 'textInput', 'a:13:{s:4:"name";s:7:"name_pt";s:7:"caption";s:9:"Name (PT)";s:8:"required";s:1:"1";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:0:"";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}', 2, 211, 0),
(2828, 'field', 'a:14:{s:4:"name";s:2:"pt";s:7:"caption";s:10:"Portuguese";s:8:"subtable";s:0:"";s:15:"subtable_fields";s:0:"";s:8:"link_url";s:0:"";s:11:"concat_char";s:0:"";s:7:"in_form";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:14:"override_value";s:0:"";s:13:"link_id_field";s:0:"";}', 3, 178, 0),
(2827, 'textInput', 'a:13:{s:4:"name";s:2:"pt";s:7:"caption";s:10:"Portuguese";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:0:"";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}', 4, 139, 0),
(2826, 'textEditor', 'a:11:{s:4:"name";s:10:"content_pt";s:7:"caption";s:12:"Content (PT)";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:7:"echo_on";s:0:"";s:5:"class";s:0:"";s:8:"is_basic";s:0:"";s:12:"allow_images";s:0:"";s:6:"height";s:0:"";s:9:"method_id";s:0:"";}', 10, 22, 0),
(2825, 'textInput', 'a:13:{s:4:"name";s:8:"title_pt";s:7:"caption";s:10:"Title (PT)";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:0:"";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}', 2, 22, 0),
(2824, 'textEditor', 'a:11:{s:4:"name";s:10:"content_pt";s:7:"caption";s:12:"Content (PT)";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:7:"echo_on";s:0:"";s:5:"class";s:0:"";s:8:"is_basic";s:0:"";s:12:"allow_images";s:1:"1";s:6:"height";s:0:"";s:9:"method_id";s:0:"";}', 11, 98, 0),
(2823, 'textInput', 'a:13:{s:4:"name";s:8:"title_pt";s:7:"caption";s:10:"Title (PT)";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:0:"";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}', 6, 98, 0);

ALTER TABLE  `currencies` ADD  `name_pt` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL AFTER  `name_zh` ;
INSERT INTO `admin_controls_methods` (`id`, `method`, `arguments`, `order`, `control_id`, `p_id`) VALUES
(2839, 'textInput', 'a:13:{s:4:"name";s:7:"name_pt";s:7:"caption";s:9:"Name (PT)";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:0:"";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}', 2, 258, 0);


UPDATE `lang` SET `id` = 9,`pt` = 'Início' WHERE `lang`.`id` = 9;
UPDATE `lang` SET `id` = 10,`pt` = 'Compre e venda Bitcoin usando 30 moedas diferentes' WHERE `lang`.`id` = 10;
UPDATE `lang` SET `id` = 11,`pt` = 'Transações' WHERE `lang`.`id` = 11;
UPDATE `lang` SET `id` = 12,`pt` = 'O que é Bitcoin?' WHERE `lang`.`id` = 12;
UPDATE `lang` SET `id` = 13,`pt` = 'Como funciona o Bitcoin' WHERE `lang`.`id` = 13;
UPDATE `lang` SET `id` = 14,`pt` = 'Bitcoins negociados' WHERE `lang`.`id` = 14;
UPDATE `lang` SET `id` = 15,`pt` = 'Como isso funciona?' WHERE `lang`.`id` = 15;
UPDATE `lang` SET `id` = 16,`pt` = 'Taxas' WHERE `lang`.`id` = 16;
UPDATE `lang` SET `id` = 17,`pt` = 'Minha conta' WHERE `lang`.`id` = 17;
UPDATE `lang` SET `id` = 18,`pt` = 'Ordens abertas' WHERE `lang`.`id` = 18;
UPDATE `lang` SET `id` = 19,`pt` = 'Transações' WHERE `lang`.`id` = 19;
UPDATE `lang` SET `id` = 20,`pt` = 'Segurança' WHERE `lang`.`id` = 20;
UPDATE `lang` SET `id` = 21,`pt` = 'Compra/Venda' WHERE `lang`.`id` = 21;
UPDATE `lang` SET `id` = 22,`pt` = 'Depósito' WHERE `lang`.`id` = 22;
UPDATE `lang` SET `id` = 23,`pt` = 'Retirada' WHERE `lang`.`id` = 23;
UPDATE `lang` SET `id` = 24,`pt` = 'Ajuda / FAQ' WHERE `lang`.`id` = 24;
UPDATE `lang` SET `id` = 25,`pt` = 'Termos de uso' WHERE `lang`.`id` = 25;
UPDATE `lang` SET `id` = 26,`pt` = 'Entre em contato' WHERE `lang`.`id` = 26;
UPDATE `lang` SET `id` = 27,`pt` = 'Entrar' WHERE `lang`.`id` = 27;
UPDATE `lang` SET `id` = 28,`pt` = 'Registrar' WHERE `lang`.`id` = 28;
UPDATE `lang` SET `id` = 29,`pt` = 'Preocupado com segurança? Leia mais sobre nossas medidas de segurança.' WHERE `lang`.`id` = 29;
UPDATE `lang` SET `id` = 30,`pt` = 'Leia mais' WHERE `lang`.`id` = 30;
UPDATE `lang` SET `id` = 31,`pt` = 'Mercado de Bitcoin<strong> Visão geral </ strong>' WHERE `lang`.`id` = 31;
UPDATE `lang` SET `id` = 32,`pt` = 'Principais estatísticas sobre o mercado de negociação [c_currency]' WHERE `lang`.`id` = 32;
UPDATE `lang` SET `id` = 33,`pt` = 'Último preço' WHERE `lang`.`id` = 33;
UPDATE `lang` SET `id` = 34,`pt` = 'Mudança diária' WHERE `lang`.`id` = 34;
UPDATE `lang` SET `id` = 35,`pt` = 'Faixa do dia' WHERE `lang`.`id` = 35;
UPDATE `lang` SET `id` = 36,`pt` = 'Abertura de hoje' WHERE `lang`.`id` = 36;
UPDATE `lang` SET `id` = 37,`pt` = '24h Volume' WHERE `lang`.`id` = 37;
UPDATE `lang` SET `id` = 38,`pt` = 'Valor de mercado' WHERE `lang`.`id` = 38;
UPDATE `lang` SET `id` = 39,`pt` = 'Total [c_currency]' WHERE `lang`.`id` = 39;
UPDATE `lang` SET `id` = 40,`pt` = 'Volume Global' WHERE `lang`.`id` = 40;
UPDATE `lang` SET `id` = 41,`pt` = '%d/%m/%y' WHERE `lang`.`id` = 41;
UPDATE `lang` SET `id` = 42,`pt` = 'Datas' WHERE `lang`.`id` = 42;
UPDATE `lang` SET `id` = 43,`pt` = 'Dom' WHERE `lang`.`id` = 43;
UPDATE `lang` SET `id` = 44,`pt` = 'Seg' WHERE `lang`.`id` = 44;
UPDATE `lang` SET `id` = 45,`pt` = 'Ter' WHERE `lang`.`id` = 45;
UPDATE `lang` SET `id` = 46,`pt` = 'Qua' WHERE `lang`.`id` = 46;
UPDATE `lang` SET `id` = 47,`pt` = 'Qui' WHERE `lang`.`id` = 47;
UPDATE `lang` SET `id` = 48,`pt` = 'Sex' WHERE `lang`.`id` = 48;
UPDATE `lang` SET `id` = 49,`pt` = 'Sáb' WHERE `lang`.`id` = 49;
UPDATE `lang` SET `id` = 50,`pt` = 'Janeiro' WHERE `lang`.`id` = 50;
UPDATE `lang` SET `id` = 51,`pt` = 'Fevereiro' WHERE `lang`.`id` = 51;
UPDATE `lang` SET `id` = 52,`pt` = 'Março' WHERE `lang`.`id` = 52;
UPDATE `lang` SET `id` = 53,`pt` = 'Abril' WHERE `lang`.`id` = 53;
UPDATE `lang` SET `id` = 54,`pt` = 'Maio' WHERE `lang`.`id` = 54;
UPDATE `lang` SET `id` = 55,`pt` = 'Junho' WHERE `lang`.`id` = 55;
UPDATE `lang` SET `id` = 56,`pt` = 'Julho' WHERE `lang`.`id` = 56;
UPDATE `lang` SET `id` = 57,`pt` = 'Agosto' WHERE `lang`.`id` = 57;
UPDATE `lang` SET `id` = 58,`pt` = 'Setembro' WHERE `lang`.`id` = 58;
UPDATE `lang` SET `id` = 59,`pt` = 'Outubro' WHERE `lang`.`id` = 59;
UPDATE `lang` SET `id` = 60,`pt` = 'Novembro' WHERE `lang`.`id` = 60;
UPDATE `lang` SET `id` = 61,`pt` = 'Dezembro' WHERE `lang`.`id` = 61;
UPDATE `lang` SET `id` = 62,`pt` = 'd/m/Y' WHERE `lang`.`id` = 62;
UPDATE `lang` SET `id` = 63,`pt` = 'Tempo desde' WHERE `lang`.`id` = 63;
UPDATE `lang` SET `id` = 64,`pt` = 'Quantidade' WHERE `lang`.`id` = 64;
UPDATE `lang` SET `id` = 65,`pt` = 'Preço' WHERE `lang`.`id` = 65;
UPDATE `lang` SET `id` = 67,`pt` = 'Últimas transações' WHERE `lang`.`id` = 67;
UPDATE `lang` SET `id` = 68,`pt` = 'Ordens abertas' WHERE `lang`.`id` = 68;
UPDATE `lang` SET `id` = 69,`pt` = 'Moeda' WHERE `lang`.`id` = 69;
UPDATE `lang` SET `id` = 70,`pt` = 'Nenhuma transação para exibir.' WHERE `lang`.`id` = 70;
UPDATE `lang` SET `id` = 71,`pt` = 'Oferta' WHERE `lang`.`id` = 71;
UPDATE `lang` SET `id` = 72,`pt` = 'Pergunta' WHERE `lang`.`id` = 72;
UPDATE `lang` SET `id` = 73,`pt` = 'Nenhum oferta para exibir.' WHERE `lang`.`id` = 73;
UPDATE `lang` SET `id` = 74,`pt` = 'Nenhuma pergunta para exibir.' WHERE `lang`.`id` = 74;
UPDATE `lang` SET `id` = 75,`pt` = 'Novidades' WHERE `lang`.`id` = 75;
UPDATE `lang` SET `id` = 76,`pt` = 'Últimas <strong>novidades</strong>' WHERE `lang`.`id` = 76;
UPDATE `lang` SET `id` = 77,`pt` = 'Notícias relevantes sobre Bitcoin e a este site em particular.' WHERE `lang`.`id` = 77;
UPDATE `lang` SET `id` = 82,`pt` = 'Navegação' WHERE `lang`.`id` = 82;
UPDATE `lang` SET `id` = 83,`pt` = 'Informações sobre Bitcoin' WHERE `lang`.`id` = 83;
UPDATE `lang` SET `id` = 84,`pt` = 'Conta' WHERE `lang`.`id` = 84;
UPDATE `lang` SET `id` = 85,`pt` = 'Leia mais novidades' WHERE `lang`.`id` = 85;
UPDATE `lang` SET `id` = 86,`pt` = 'Ir para o Registro de Transações' WHERE `lang`.`id` = 86;
UPDATE `lang` SET `id` = 87,`pt` = 'Preço' WHERE `lang`.`id` = 87;
UPDATE `lang` SET `id` = 88,`pt` = 'Quantidade' WHERE `lang`.`id` = 88;
UPDATE `lang` SET `id` = 89,`pt` = 'Valor' WHERE `lang`.`id` = 89;
UPDATE `lang` SET `id` = 90,`pt` = 'Perdeu suas informações de login?' WHERE `lang`.`id` = 90;
UPDATE `lang` SET `id` = 91,`pt` = 'Ainda não tem uma conta? Registre-se aqui.' WHERE `lang`.`id` = 91;
UPDATE `lang` SET `id` = 92,`pt` = 'Você deve fornecer um nome de usuário.' WHERE `lang`.`id` = 92;
UPDATE `lang` SET `id` = 93,`pt` = 'Você deve fornecer uma senha.' WHERE `lang`.`id` = 93;
UPDATE `lang` SET `id` = 94,`pt` = 'Informações de login inválidas.' WHERE `lang`.`id` = 94;
UPDATE `lang` SET `id` = 95,`pt` = 'Esqueceu a senha?' WHERE `lang`.`id` = 95;
UPDATE `lang` SET `id` = 96,`pt` = 'Esqueceu-se das suas informações de início de sessão? Insira seu e-mail para redefinir sua senha.' WHERE `lang`.`id` = 96;
UPDATE `lang` SET `id` = 97,`pt` = 'Gerar solicitação' WHERE `lang`.`id` = 97;
UPDATE `lang` SET `id` = 98,`pt` = 'Lembrou-se da sua informação? Clique aqui para retornar ao login.' WHERE `lang`.`id` = 98;
UPDATE `lang` SET `id` = 99,`pt` = 'Ocorreu um erro eo email não pôde ser enviado. Por favor, tente novamente mais tarde.' WHERE `lang`.`id` = 99;
UPDATE `lang` SET `id` = 100,`pt` = 'Endereço de email invalido.' WHERE `lang`.`id` = 100;
UPDATE `lang` SET `id` = 101,`pt` = 'O email foi enviado com sucesso.' WHERE `lang`.`id` = 101;
UPDATE `lang` SET `id` = 102,`pt` = 'Você recebeu um pedido de redefinição de senha. Por favor verifique seu email.' WHERE `lang`.`id` = 102;
UPDATE `lang` SET `id` = 103,`pt` = 'Não existe uma conta para o endereço de e-mail que especificou.' WHERE `lang`.`id` = 103;
UPDATE `lang` SET `id` = 104,`pt` = 'Configurações' WHERE `lang`.`id` = 104;
UPDATE `lang` SET `id` = 105,`pt` = 'Navegação na Conta' WHERE `lang`.`id` = 105;
UPDATE `lang` SET `id` = 106,`pt` = 'Bem vindo' WHERE `lang`.`id` = 106;
UPDATE `lang` SET `id` = 107,`pt` = 'Saldos disponíveis' WHERE `lang`.`id` = 107;
UPDATE `lang` SET `id` = 109,`pt` = 'Saldos em espera' WHERE `lang`.`id` = 109;
UPDATE `lang` SET `id` = 110,`pt` = 'disponível' WHERE `lang`.`id` = 110;
UPDATE `lang` SET `id` = 111,`pt` = 'Em ordens abertas' WHERE `lang`.`id` = 111;
UPDATE `lang` SET `id` = 112,`pt` = 'Aguardando retirada' WHERE `lang`.`id` = 112;
UPDATE `lang` SET `id` = 113,`pt` = 'Nível de Taxa e Volume' WHERE `lang`.`id` = 113;
UPDATE `lang` SET `id` = 114,`pt` = 'Taxa da Comissão (taker)' WHERE `lang`.`id` = 114;
UPDATE `lang` SET `id` = 115,`pt` = 'Volume de 30 dias em [currency]' WHERE `lang`.`id` = 115;
UPDATE `lang` SET `id` = 116,`pt` = 'Ver tabela de taxas' WHERE `lang`.`id` = 116;
UPDATE `lang` SET `id` = 117,`pt` = 'Editar esta ordem' WHERE `lang`.`id` = 117;
UPDATE `lang` SET `id` = 118,`pt` = 'Filtrar por moeda' WHERE `lang`.`id` = 118;
UPDATE `lang` SET `id` = 119,`pt` = 'Ordenar por' WHERE `lang`.`id` = 119;
UPDATE `lang` SET `id` = 120,`pt` = 'Preço do pedido' WHERE `lang`.`id` = 120;
UPDATE `lang` SET `id` = 121,`pt` = 'Data / hora do pedido' WHERE `lang`.`id` = 121;
UPDATE `lang` SET `id` = 122,`pt` = 'Valor do pedido' WHERE `lang`.`id` = 122;
UPDATE `lang` SET `id` = 123,`pt` = 'Tipo' WHERE `lang`.`id` = 123;
UPDATE `lang` SET `id` = 124,`pt` = 'Data e hora' WHERE `lang`.`id` = 124;
UPDATE `lang` SET `id` = 125,`pt` = '[c_currency] Total' WHERE `lang`.`id` = 125;
UPDATE `lang` SET `id` = 126,`pt` = 'Valor' WHERE `lang`.`id` = 126;
UPDATE `lang` SET `id` = 127,`pt` = 'Preço' WHERE `lang`.`id` = 127;
UPDATE `lang` SET `id` = 128,`pt` = 'Taxa' WHERE `lang`.`id` = 128;
UPDATE `lang` SET `id` = 129,`pt` = 'Qualquer' WHERE `lang`.`id` = 129;
UPDATE `lang` SET `id` = 130,`pt` = 'Mostrando [results] transações em [num_pages] páginas.' WHERE `lang`.`id` = 130;
UPDATE `lang` SET `id` = 131,`pt` = 'Top 10 Compradores' WHERE `lang`.`id` = 131;
UPDATE `lang` SET `id` = 132,`pt` = 'Top 10 Vendedores' WHERE `lang`.`id` = 132;
UPDATE `lang` SET `id` = 133,`pt` = 'Compre [c_currency]' WHERE `lang`.`id` = 133;
UPDATE `lang` SET `id` = 134,`pt` = 'Venda [c_currency]' WHERE `lang`.`id` = 134;
UPDATE `lang` SET `id` = 135,`pt` = 'Clique para iniciar' WHERE `lang`.`id` = 135;
UPDATE `lang` SET `id` = 136,`pt` = 'Quantidade a comprar' WHERE `lang`.`id` = 136;
UPDATE `lang` SET `id` = 137,`pt` = 'Moeda para uso' WHERE `lang`.`id` = 137;
UPDATE `lang` SET `id` = 138,`pt` = 'Preço' WHERE `lang`.`id` = 138;
UPDATE `lang` SET `id` = 139,`pt` = 'Quantidade a vender' WHERE `lang`.`id` = 139;
UPDATE `lang` SET `id` = 140,`pt` = 'Subtotal' WHERE `lang`.`id` = 140;
UPDATE `lang` SET `id` = 141,`pt` = 'Taxa' WHERE `lang`.`id` = 141;
UPDATE `lang` SET `id` = 142,`pt` = '[c_currency] para receber' WHERE `lang`.`id` = 142;
UPDATE `lang` SET `id` = 143,`pt` = '[currency] para receber' WHERE `lang`.`id` = 143;
UPDATE `lang` SET `id` = 144,`pt` = 'Comprar a preço de mercado' WHERE `lang`.`id` = 144;
UPDATE `lang` SET `id` = 145,`pt` = 'Vendar a preço de mercado' WHERE `lang`.`id` = 145;
UPDATE `lang` SET `id` = 146,`pt` = 'Clique para obter informações sobre como isso funciona.' WHERE `lang`.`id` = 146;
UPDATE `lang` SET `id` = 147,`pt` = 'Aprox. [currency] para gastar' WHERE `lang`.`id` = 147;
UPDATE `lang` SET `id` = 148,`pt` = 'Aprox. [currency] para receber' WHERE `lang`.`id` = 148;
UPDATE `lang` SET `id` = 149,`pt` = 'Você deve comprar uma quantidade maior do que zero.' WHERE `lang`.`id` = 149;
UPDATE `lang` SET `id` = 150,`pt` = 'Você deve especificar um preço ao qual comprar.' WHERE `lang`.`id` = 150;
UPDATE `lang` SET `id` = 151,`pt` = 'Você deve especificar um preço para vender.' WHERE `lang`.`id` = 151;
UPDATE `lang` SET `id` = 152,`pt` = 'Nenhuma moeda especificada.' WHERE `lang`.`id` = 152;
UPDATE `lang` SET `id` = 153,`pt` = 'Você não tem o suficiente da moeda especificada.' WHERE `lang`.`id` = 153;
UPDATE `lang` SET `id` = 154,`pt` = 'Você não tem [c_currency] suficiente.' WHERE `lang`.`id` = 154;
UPDATE `lang` SET `id` = 155,`pt` = 'Sair' WHERE `lang`.`id` = 155;
UPDATE `lang` SET `id` = 156,`pt` = 'Você não tem pedidos em aberto ou retirada.' WHERE `lang`.`id` = 156;
UPDATE `lang` SET `id` = 157,`pt` = 'Disponível [currency]' WHERE `lang`.`id` = 157;
UPDATE `lang` SET `id` = 158,`pt` = 'Disponível [c_currency]' WHERE `lang`.`id` = 158;
UPDATE `lang` SET `id` = 159,`pt` = 'Você fez [transactions] novas transações.' WHERE `lang`.`id` = 159;
UPDATE `lang` SET `id` = 160,`pt` = 'Você criou uma nova ordem e realizou [transactions] novas transações.' WHERE `lang`.`id` = 160;
UPDATE `lang` SET `id` = 161,`pt` = 'Editar ordem' WHERE `lang`.`id` = 161;
UPDATE `lang` SET `id` = 162,`pt` = 'Você criou uma nova ordem.' WHERE `lang`.`id` = 162;
UPDATE `lang` SET `id` = 163,`pt` = 'Seu pedido foi editado com sucesso.' WHERE `lang`.`id` = 163;
UPDATE `lang` SET `id` = 164,`pt` = 'Você editou seu pedido e realizou [transactions] novas transações.' WHERE `lang`.`id` = 164;
UPDATE `lang` SET `id` = 165,`pt` = 'Você fez esta ordem' WHERE `lang`.`id` = 165;
UPDATE `lang` SET `id` = 166,`pt` = 'Visão geral' WHERE `lang`.`id` = 166;
UPDATE `lang` SET `id` = 167,`pt` = 'Ativar a autenticação de dois fatores' WHERE `lang`.`id` = 167;
UPDATE `lang` SET `id` = 168,`pt` = 'Seu país' WHERE `lang`.`id` = 168;
UPDATE `lang` SET `id` = 169,`pt` = 'O seu celular #' WHERE `lang`.`id` = 169;
UPDATE `lang` SET `id` = 170,`pt` = 'Habilitar 2FA' WHERE `lang`.`id` = 170;
UPDATE `lang` SET `id` = 171,`pt` = 'Você deve fornecer um número de telefone celular.' WHERE `lang`.`id` = 171;
UPDATE `lang` SET `id` = 172,`pt` = 'Você deve selecionar um país.' WHERE `lang`.`id` = 172;
UPDATE `lang` SET `id` = 173,`pt` = 'O servidor de autenticação nao foi localizado. Por favor, tente novamente mais tarde.' WHERE `lang`.`id` = 173;
UPDATE `lang` SET `id` = 174,`pt` = 'Inserir token' WHERE `lang`.`id` = 174;
UPDATE `lang` SET `id` = 175,`pt` = 'Seu token' WHERE `lang`.`id` = 175;
UPDATE `lang` SET `id` = 176,`pt` = 'Validade' WHERE `lang`.`id` = 176;
UPDATE `lang` SET `id` = 177,`pt` = 'Insira o token do aplicativo 2FA.' WHERE `lang`.`id` = 177;
UPDATE `lang` SET `id` = 178,`pt` = 'Parabéns. Agora você está configurado para usar a autenticação de dois fatores.' WHERE `lang`.`id` = 178;
UPDATE `lang` SET `id` = 179,`pt` = 'Verificado' WHERE `lang`.`id` = 179;
UPDATE `lang` SET `id` = 180,`pt` = 'Trocar número' WHERE `lang`.`id` = 180;
UPDATE `lang` SET `id` = 181,`pt` = 'Enviar por SMS' WHERE `lang`.`id` = 181;
UPDATE `lang` SET `id` = 182,`pt` = 'Não me pergunte por isso por 30 dias' WHERE `lang`.`id` = 182;
UPDATE `lang` SET `id` = 183,`pt` = 'Autenticação' WHERE `lang`.`id` = 183;
UPDATE `lang` SET `id` = 184,`pt` = 'é um campo obrigatório.' WHERE `lang`.`id` = 184;
UPDATE `lang` SET `id` = 185,`pt` = 'Você deve digitar um e-mail válido.' WHERE `lang`.`id` = 185;
UPDATE `lang` SET `id` = 186,`pt` = 'Sua senha deve ter pelo menos 8 caracteres. A maioria dos caracteres especiais são permitidos.' WHERE `lang`.`id` = 186;
UPDATE `lang` SET `id` = 187,`pt` = 'Informação pessoal' WHERE `lang`.`id` = 187;
UPDATE `lang` SET `id` = 188,`pt` = 'Alterar senha' WHERE `lang`.`id` = 188;
UPDATE `lang` SET `id` = 189,`pt` = 'Confirmar senha' WHERE `lang`.`id` = 189;
UPDATE `lang` SET `id` = 190,`pt` = 'Primeiro nome' WHERE `lang`.`id` = 190;
UPDATE `lang` SET `id` = 191,`pt` = 'Sobrenome' WHERE `lang`.`id` = 191;
UPDATE `lang` SET `id` = 192,`pt` = 'País' WHERE `lang`.`id` = 192;
UPDATE `lang` SET `id` = 193,`pt` = 'Email' WHERE `lang`.`id` = 193;
UPDATE `lang` SET `id` = 194,`pt` = 'Salvar informações' WHERE `lang`.`id` = 194;
UPDATE `lang` SET `id` = 195,`pt` = 'Suas informações pessoais foram atualizadas.' WHERE `lang`.`id` = 195;
UPDATE `lang` SET `id` = 196,`pt` = 'Confirme as retiradas de criptografia com autenticação de dois fatores.' WHERE `lang`.`id` = 196;
UPDATE `lang` SET `id` = 197,`pt` = 'Confirme as retiradas de criptografia por e-mail.' WHERE `lang`.`id` = 197;
UPDATE `lang` SET `id` = 198,`pt` = 'Confirmar retiradas bancárias com autenticação de dois fatores.' WHERE `lang`.`id` = 198;
UPDATE `lang` SET `id` = 199,`pt` = 'Confirme as retiradas bancárias por e-mail.' WHERE `lang`.`id` = 199;
UPDATE `lang` SET `id` = 200,`pt` = 'Notificar por e-mail quando os depósitos de criptografia são feitos.' WHERE `lang`.`id` = 200;
UPDATE `lang` SET `id` = 201,`pt` = 'Notificar por e-mail quando os depósitos bancários são feitos.' WHERE `lang`.`id` = 201;
UPDATE `lang` SET `id` = 202,`pt` = 'Segurança e Notificações' WHERE `lang`.`id` = 202;
UPDATE `lang` SET `id` = 203,`pt` = 'Salvar configurações' WHERE `lang`.`id` = 203;
UPDATE `lang` SET `id` = 204,`pt` = 'Taxa do comprador' WHERE `lang`.`id` = 204;
UPDATE `lang` SET `id` = 205,`pt` = 'Volume de 30 dias em' WHERE `lang`.`id` = 205;
UPDATE `lang` SET `id` = 206,`pt` = 'Para consultas gerais' WHERE `lang`.`id` = 206;
UPDATE `lang` SET `id` = 207,`pt` = 'Companhia' WHERE `lang`.`id` = 207;
UPDATE `lang` SET `id` = 208,`pt` = 'Assunto' WHERE `lang`.`id` = 208;
UPDATE `lang` SET `id` = 209,`pt` = 'Sua mensagem' WHERE `lang`.`id` = 209;
UPDATE `lang` SET `id` = 210,`pt` = 'Copie o texto de confirmação' WHERE `lang`.`id` = 210;
UPDATE `lang` SET `id` = 211,`pt` = 'Enviar mensagem' WHERE `lang`.`id` = 211;
UPDATE `lang` SET `id` = 212,`pt` = 'O texto de confirmação não corresponde à imagem.' WHERE `lang`.`id` = 212;
UPDATE `lang` SET `id` = 213,`pt` = 'Ocorreu um erro eo email não pôde ser enviado. Por favor, tente novamente mais tarde.' WHERE `lang`.`id` = 213;
UPDATE `lang` SET `id` = 214,`pt` = 'Obrigado por entrar em contato conosco. Responderemos à sua mensagem o mais rapidamente possível.' WHERE `lang`.`id` = 214;
UPDATE `lang` SET `id` = 215,`pt` = 'Contas bancárias' WHERE `lang`.`id` = 215;
UPDATE `lang` SET `id` = 216,`pt` = 'Adicionar Conta' WHERE `lang`.`id` = 216;
UPDATE `lang` SET `id` = 217,`pt` = 'Número da conta' WHERE `lang`.`id` = 217;
UPDATE `lang` SET `id` = 218,`pt` = 'Descrição' WHERE `lang`.`id` = 218;
UPDATE `lang` SET `id` = 219,`pt` = 'Remover' WHERE `lang`.`id` = 219;
UPDATE `lang` SET `id` = 220,`pt` = 'Não há contas bancárias associadas ao seu perfil.' WHERE `lang`.`id` = 220;
UPDATE `lang` SET `id` = 221,`pt` = 'Adicionar Conta da Crypto Capital' WHERE `lang`.`id` = 221;
UPDATE `lang` SET `id` = 222,`pt` = 'Número da conta da Crypto Capital' WHERE `lang`.`id` = 222;
UPDATE `lang` SET `id` = 223,`pt` = 'Adicionar conta' WHERE `lang`.`id` = 223;
UPDATE `lang` SET `id` = 224,`pt` = 'Essa conta já está associada ao seu perfil.' WHERE `lang`.`id` = 224;
UPDATE `lang` SET `id` = 225,`pt` = 'Número de conta inválido.' WHERE `lang`.`id` = 225;
UPDATE `lang` SET `id` = 226,`pt` = 'Conta da Crypto Capital' WHERE `lang`.`id` = 226;
UPDATE `lang` SET `id` = 227,`pt` = 'A conta foi adicionada com êxito.' WHERE `lang`.`id` = 227;
UPDATE `lang` SET `id` = 228,`pt` = 'A conta especificada não está associada ao seu perfil.' WHERE `lang`.`id` = 228;
UPDATE `lang` SET `id` = 229,`pt` = 'A conta foi removida com êxito.' WHERE `lang`.`id` = 229;
UPDATE `lang` SET `id` = 230,`pt` = 'Funções de conta' WHERE `lang`.`id` = 230;
UPDATE `lang` SET `id` = 231,`pt` = 'Endereço criptografado' WHERE `lang`.`id` = 231;
UPDATE `lang` SET `id` = 232,`pt` = 'Obter um novo endereço' WHERE `lang`.`id` = 232;
UPDATE `lang` SET `id` = 233,`pt` = 'Data e hora' WHERE `lang`.`id` = 233;
UPDATE `lang` SET `id` = 234,`pt` = 'Endereço' WHERE `lang`.`id` = 234;
UPDATE `lang` SET `id` = 235,`pt` = 'Você não tem endereços Bitcoin. Gere um novo.' WHERE `lang`.`id` = 235;
UPDATE `lang` SET `id` = 236,`pt` = 'Um novo endereço foi adicionado.' WHERE `lang`.`id` = 236;
UPDATE `lang` SET `id` = 237,`pt` = 'Você só pode adicionar um novo endereço Bitcoin a cada 24 horas.' WHERE `lang`.`id` = 237;
UPDATE `lang` SET `id` = 238,`pt` = 'Você deve especificar a moeda da conta.' WHERE `lang`.`id` = 238;
UPDATE `lang` SET `id` = 239,`pt` = 'Moeda' WHERE `lang`.`id` = 239;
UPDATE `lang` SET `id` = 240,`pt` = 'Essa conta já está associada a outro perfil.' WHERE `lang`.`id` = 240;
UPDATE `lang` SET `id` = 241,`pt` = 'Depósitos criptografados' WHERE `lang`.`id` = 241;
UPDATE `lang` SET `id` = 242,`pt` = 'Enviar para este endereço' WHERE `lang`.`id` = 242;
UPDATE `lang` SET `id` = 243,`pt` = 'Gerenciar endereços criptografados' WHERE `lang`.`id` = 243;
UPDATE `lang` SET `id` = 244,`pt` = 'Depósito em moeda fiat' WHERE `lang`.`id` = 244;
UPDATE `lang` SET `id` = 245,`pt` = 'Conta bancária a ser usada' WHERE `lang`.`id` = 245;
UPDATE `lang` SET `id` = 246,`pt` = 'Gerenciar contas bancárias' WHERE `lang`.`id` = 246;
UPDATE `lang` SET `id` = 247,`pt` = 'Depósitos Recentes' WHERE `lang`.`id` = 247;
UPDATE `lang` SET `id` = 248,`pt` = 'Data e hora' WHERE `lang`.`id` = 248;
UPDATE `lang` SET `id` = 249,`pt` = 'Descrição' WHERE `lang`.`id` = 249;
UPDATE `lang` SET `id` = 250,`pt` = 'Quantidade' WHERE `lang`.`id` = 250;
UPDATE `lang` SET `id` = 251,`pt` = 'Status' WHERE `lang`.`id` = 251;
UPDATE `lang` SET `id` = 252,`pt` = 'Retirar moeda digital' WHERE `lang`.`id` = 252;
UPDATE `lang` SET `id` = 253,`pt` = 'Enviar para endereço' WHERE `lang`.`id` = 253;
UPDATE `lang` SET `id` = 254,`pt` = 'Quantidade a enviar' WHERE `lang`.`id` = 254;
UPDATE `lang` SET `id` = 255,`pt` = 'Enviar' WHERE `lang`.`id` = 255;
UPDATE `lang` SET `id` = 256,`pt` = 'Retirar moeda fiat' WHERE `lang`.`id` = 256;
UPDATE `lang` SET `id` = 257,`pt` = 'Recebendo Conta Bancária' WHERE `lang`.`id` = 257;
UPDATE `lang` SET `id` = 258,`pt` = 'Moeda de retirada' WHERE `lang`.`id` = 258;
UPDATE `lang` SET `id` = 259,`pt` = 'Quantidade à sacar' WHERE `lang`.`id` = 259;
UPDATE `lang` SET `id` = 260,`pt` = 'Moeda de retirada' WHERE `lang`.`id` = 260;
UPDATE `lang` SET `id` = 261,`pt` = 'Você não fez depósitos.' WHERE `lang`.`id` = 261;
UPDATE `lang` SET `id` = 262,`pt` = 'Nenhuma retirada foi feita.' WHERE `lang`.`id` = 262;
UPDATE `lang` SET `id` = 263,`pt` = 'Você deve especificar a conta de retirada.' WHERE `lang`.`id` = 263;
UPDATE `lang` SET `id` = 264,`pt` = 'A conta especificada não existe.' WHERE `lang`.`id` = 264;
UPDATE `lang` SET `id` = 265,`pt` = 'Especifique um valor para retirada maior do que zero.' WHERE `lang`.`id` = 265;
UPDATE `lang` SET `id` = 266,`pt` = 'A conta especificada não está associada ao seu perfil.' WHERE `lang`.`id` = 266;
UPDATE `lang` SET `id` = 267,`pt` = 'O valor da retirada excede os fundos disponíveis.' WHERE `lang`.`id` = 267;
UPDATE `lang` SET `id` = 268,`pt` = 'São necessárias outras medidas para autorizar este pedido. Siga o link que você recebeu em seu e-mail para autorizar esta transação.' WHERE `lang`.`id` = 268;
UPDATE `lang` SET `id` = 269,`pt` = 'Uma mensagem SMS foi enviada para você com o código de autorização.' WHERE `lang`.`id` = 269;
UPDATE `lang` SET `id` = 270,`pt` = 'Seu pedido de retirada foi autorizado com êxito.' WHERE `lang`.`id` = 270;
UPDATE `lang` SET `id` = 271,`pt` = 'Reenviar SMS' WHERE `lang`.`id` = 271;
UPDATE `lang` SET `id` = 272,`pt` = 'Você especificou um endereço inválido [c_currency].' WHERE `lang`.`id` = 272;
UPDATE `lang` SET `id` = 273,`pt` = 'Seu pedido de retirada foi criado com êxito. Seu cripto será enviado em breve.' WHERE `lang`.`id` = 273;
UPDATE `lang` SET `id` = 274,`pt` = 'Ocorreu um erro e sua transação não pôde ser enviada. Por favor, tente novamente mais tarde.' WHERE `lang`.`id` = 274;
UPDATE `lang` SET `id` = 275,`pt` = 'Sua retirada do Bitcoin foi enviada com sucesso.' WHERE `lang`.`id` = 275;
UPDATE `lang` SET `id` = 276,`pt` = 'Seu pedido de retirada foi criado com êxito.' WHERE `lang`.`id` = 276;
UPDATE `lang` SET `id` = 277,`pt` = 'Nome de usuário' WHERE `lang`.`id` = 277;
UPDATE `lang` SET `id` = 278,`pt` = 'Já existe uma conta associada a esse endereço de e-mail.' WHERE `lang`.`id` = 278;
UPDATE `lang` SET `id` = 279,`pt` = 'Informações de Registro' WHERE `lang`.`id` = 279;
UPDATE `lang` SET `id` = 280,`pt` = 'Obrigado por se registar para utilizar [exchange_name]! Seu nome de usuário e senha lhe foram enviados por e-mail.' WHERE `lang`.`id` = 280;
UPDATE `lang` SET `id` = 281,`pt` = 'Erro: O pedido expirou.' WHERE `lang`.`id` = 281;
UPDATE `lang` SET `id` = 282,`pt` = 'Suas configurações pessoais foram atualizadas.' WHERE `lang`.`id` = 282;
UPDATE `lang` SET `id` = 283,`pt` = 'Recomenda-se que configure a autenticação de dois factores para a sua conta utilizando o telemóvel. Para isso, visite <a href="security.php"> a página de segurança </a>.' WHERE `lang`.`id` = 283;
UPDATE `lang` SET `id` = 284,`pt` = 'Você deve inserir um valor maior que zero para vender.' WHERE `lang`.`id` = 284;
UPDATE `lang` SET `id` = 285,`pt` = 'São necessárias mais ações para autorizar essas mudanças. Por favor, siga o link que você recebeu em seu e-mail para autorizar.' WHERE `lang`.`id` = 285;
UPDATE `lang` SET `id` = 286,`pt` = 'A senha que você inseriu não corresponde à verificação.' WHERE `lang`.`id` = 286;
UPDATE `lang` SET `id` = 287,`pt` = 'Dowload do arquivo de transações em formato CSV' WHERE `lang`.`id` = 287;
UPDATE `lang` SET `id` = 288,`pt` = 'Primeiro login' WHERE `lang`.`id` = 288;
UPDATE `lang` SET `id` = 289,`pt` = 'Definir senha' WHERE `lang`.`id` = 289;
UPDATE `lang` SET `id` = 290,`pt` = 'Personalizar senha' WHERE `lang`.`id` = 290;
UPDATE `lang` SET `id` = 291,`pt` = 'Especifique uma senha para sua nova conta. Se não o fizer, ainda poderá alterá-lo mais tarde na página de definições.' WHERE `lang`.`id` = 291;
UPDATE `lang` SET `id` = 292,`pt` = 'Notificar por e-mail quando alguém fizer login na sua conta.' WHERE `lang`.`id` = 292;
UPDATE `lang` SET `id` = 293,`pt` = 'Cancelar esta ordem' WHERE `lang`.`id` = 293;
UPDATE `lang` SET `id` = 294,`pt` = 'Você não pode cancelar a ordem de outra pessoa.' WHERE `lang`.`id` = 294;
UPDATE `lang` SET `id` = 295,`pt` = 'A ordem selecionada foi cancelada.' WHERE `lang`.`id` = 295;
UPDATE `lang` SET `id` = 296,`pt` = 'A ordem que você especificou já foi executada ou não existe.' WHERE `lang`.`id` = 296;
UPDATE `lang` SET `id` = 297,`pt` = 'Confirmar Detalhes da Transação' WHERE `lang`.`id` = 297;
UPDATE `lang` SET `id` = 298,`pt` = 'Confirmar compra' WHERE `lang`.`id` = 298;
UPDATE `lang` SET `id` = 299,`pt` = 'Confirmar venda' WHERE `lang`.`id` = 299;
UPDATE `lang` SET `id` = 300,`pt` = 'Voltar' WHERE `lang`.`id` = 300;
UPDATE `lang` SET `id` = 301,`pt` = 'Aceito os <a href="terms.php"> termos e condições </a> de utilização deste site.' WHERE `lang`.`id` = 301;
UPDATE `lang` SET `id` = 302,`pt` = 'Você deve aceitar os <a href="terms.php"> termos de uso </a> para se cadastrar.' WHERE `lang`.`id` = 302;
UPDATE `lang` SET `id` = 303,`pt` = 'Desativar minha conta' WHERE `lang`.`id` = 303;
UPDATE `lang` SET `id` = 304,`pt` = 'Ao clicar neste botão, pode desactivar a sua conta. Se você mudar de idéia, você pode reativar sua conta a qualquer momento, fazendo login.' WHERE `lang`.`id` = 304;
UPDATE `lang` SET `id` = 305,`pt` = 'Sua conta foi desativada. Lembre-se que você pode reativar novamente a partir desta página se você decidir fazê-lo ..' WHERE `lang`.`id` = 305;
UPDATE `lang` SET `id` = 306,`pt` = 'As contas que ainda têm fundos no BTC ou em qualquer outra moeda não podem ser desativadas.' WHERE `lang`.`id` = 306;
UPDATE `lang` SET `id` = 307,`pt` = 'Reativar minha conta' WHERE `lang`.`id` = 307;
UPDATE `lang` SET `id` = 308,`pt` = 'Ao clicar neste botão, você pode reativar sua conta desativada, permitindo que todas as funcionalidades sejam novamente exibidas.' WHERE `lang`.`id` = 308;
UPDATE `lang` SET `id` = 309,`pt` = 'Sua conta foi reativada com êxito.' WHERE `lang`.`id` = 309;
UPDATE `lang` SET `id` = 310,`pt` = 'Bloquear Minha Conta' WHERE `lang`.`id` = 310;
UPDATE `lang` SET `id` = 311,`pt` = 'Ao clicar neste botão, você pode bloquear sua conta para que todas as ações sejam desativadas. Você pode desbloqueá-lo a partir desta mesma página.' WHERE `lang`.`id` = 311;
UPDATE `lang` SET `id` = 312,`pt` = 'Desbloquear minha conta' WHERE `lang`.`id` = 312;
UPDATE `lang` SET `id` = 313,`pt` = 'Ao clicar neste botão, você pode desbloquear sua conta e reativar todas as funcionalidades.' WHERE `lang`.`id` = 313;
UPDATE `lang` SET `id` = 314,`pt` = 'Sua conta foi bloqueada. Você pode desbloqueá-lo visitando esta mesma página.' WHERE `lang`.`id` = 314;
UPDATE `lang` SET `id` = 315,`pt` = 'Sua conta agora está desbloqueada.' WHERE `lang`.`id` = 315;
UPDATE `lang` SET `id` = 316,`pt` = 'Protegendo sua conta' WHERE `lang`.`id` = 316;
UPDATE `lang` SET `id` = 317,`pt` = 'Financiamento da sua conta' WHERE `lang`.`id` = 317;
UPDATE `lang` SET `id` = 318,`pt` = 'Retirando Fundos' WHERE `lang`.`id` = 318;
UPDATE `lang` SET `id` = 319,`pt` = 'Lembre-se de abrir uma conta em [currency] para que você possa retirar a moeda que receberá desta transação.' WHERE `lang`.`id` = 319;
UPDATE `lang` SET `id` = 320,`pt` = 'Todas' WHERE `lang`.`id` = 320;
UPDATE `lang` SET `id` = 321,`pt` = 'Retiradas Recentes' WHERE `lang`.`id` = 321;
UPDATE `lang` SET `id` = 322,`pt` = 'Ativar o Google Authenticator' WHERE `lang`.`id` = 322;
UPDATE `lang` SET `id` = 323,`pt` = 'Verificar o autenticador do Google' WHERE `lang`.`id` = 323;
UPDATE `lang` SET `id` = 324,`pt` = 'Código secreto' WHERE `lang`.`id` = 324;
UPDATE `lang` SET `id` = 325,`pt` = 'Opcional para o Google Authenticator.' WHERE `lang`.`id` = 325;
UPDATE `lang` SET `id` = 326,`pt` = 'Token inválido.' WHERE `lang`.`id` = 326;
UPDATE `lang` SET `id` = 327,`pt` = 'Desabilitando 2FA' WHERE `lang`.`id` = 327;
UPDATE `lang` SET `id` = 328,`pt` = 'Sua conta não está mais protegida por autenticação de dois fatores.' WHERE `lang`.`id` = 328;
UPDATE `lang` SET `id` = 329,`pt` = 'Resetando 2FA' WHERE `lang`.`id` = 329;
UPDATE `lang` SET `id` = 330,`pt` = 'Você não pode criar uma ordem de mercado porque não há pedidos compatíveis disponíveis.' WHERE `lang`.`id` = 330;
UPDATE `lang` SET `id` = 331,`pt` = 'A quantidade mínima de pedido é [fa_symbol] [amount].' WHERE `lang`.`id` = 331;
UPDATE `lang` SET `id` = 332,`pt` = 'Histórico' WHERE `lang`.`id` = 332;
UPDATE `lang` SET `id` = 333,`pt` = 'Endereço de IP' WHERE `lang`.`id` = 333;
UPDATE `lang` SET `id` = 334,`pt` = 'Você não pode comprar mais do que você está vendendo, ou vender mais baixo do que você está comprando.' WHERE `lang`.`id` = 334;
UPDATE `lang` SET `id` = 335,`pt` = 'O preço de parada deve ser maior do que o atual.' WHERE `lang`.`id` = 335;
UPDATE `lang` SET `id` = 336,`pt` = 'O preço de parada deve ser inferior ao atual.' WHERE `lang`.`id` = 336;
UPDATE `lang` SET `id` = 337,`pt` = 'Preço de parada' WHERE `lang`.`id` = 337;
UPDATE `lang` SET `id` = 338,`pt` = 'Parar ordem' WHERE `lang`.`id` = 338;
UPDATE `lang` SET `id` = 339,`pt` = 'Limitar ordem' WHERE `lang`.`id` = 339;
UPDATE `lang` SET `id` = 340,`pt` = 'Limitar preço' WHERE `lang`.`id` = 340;
UPDATE `lang` SET `id` = 341,`pt` = 'O preço de parada deve ser superior ao preço limite.' WHERE `lang`.`id` = 341;
UPDATE `lang` SET `id` = 342,`pt` = 'O preço de parada deve ser inferior ao preço limite.' WHERE `lang`.`id` = 342;
UPDATE `lang` SET `id` = 343,`pt` = 'Você deve inserir um preço de parada.' WHERE `lang`.`id` = 343;
UPDATE `lang` SET `id` = 344,`pt` = 'Você está colocando duas ordens vinculadas. A execução de um cancelará o outro (OCO).' WHERE `lang`.`id` = 344;
UPDATE `lang` SET `id` = 345,`pt` = 'Sua ordem de limite está muito longe do preço de mercado.' WHERE `lang`.`id` = 345;
UPDATE `lang` SET `id` = 346,`pt` = 'Você não pode colocar uma ordem limite para comprar sob o preço de sua venda pára.' WHERE `lang`.`id` = 346;
UPDATE `lang` SET `id` = 347,`pt` = 'Você não pode colocar uma ordem de parar para vender a um preço mais elevado do que você está comprando.' WHERE `lang`.`id` = 347;
UPDATE `lang` SET `id` = 348,`pt` = 'Sobre [exchange_name]' WHERE `lang`.`id` = 348;
UPDATE `lang` SET `id` = 349,`pt` = '' WHERE `lang`.`id` = 349;
UPDATE `lang` SET `id` = 350,`pt` = 'Convertido de [currency].' WHERE `lang`.`id` = 350;
UPDATE `lang` SET `id` = 351,`pt` = 'Taxa da Comissão' WHERE `lang`.`id` = 351;
UPDATE `lang` SET `id` = 352,`pt` = 'Volume de 24 horas [c_currency] em toda a bolsa' WHERE `lang`.`id` = 352;
UPDATE `lang` SET `id` = 353,`pt` = 'O preço mínimo é [price] devido ao seu pedido numa moeda diferente.' WHERE `lang`.`id` = 353;
UPDATE `lang` SET `id` = 354,`pt` = 'O preço máximo é [price] devido ao seu pedido numa moeda diferente.' WHERE `lang`.`id` = 354;
UPDATE `lang` SET `id` = 355,`pt` = 'Taxa do fabricante' WHERE `lang`.`id` = 355;
UPDATE `lang` SET `id` = 356,`pt` = 'FLC * - Volume Global 24h' WHERE `lang`.`id` = 356;
UPDATE `lang` SET `id` = 357,`pt` = 'Nossa segurança' WHERE `lang`.`id` = 357;
UPDATE `lang` SET `id` = 358,`pt` = 'Moeda Padrão' WHERE `lang`.`id` = 358;
UPDATE `lang` SET `id` = 360,`pt` = 'Nosso desafio comercial está começando em [tempo]. Registre-se agora para ganhar até <strong> 5 bitcoins </ strong>!' WHERE `lang`.`id` = 360;
UPDATE `lang` SET `id` = 361,`pt` = '[time] até o final da nossa concorrência comercial!' WHERE `lang`.`id` = 361;
UPDATE `lang` SET `id` = 362,`pt` = 'Pré-registro está aberto agora!' WHERE `lang`.`id` = 362;
UPDATE `lang` SET `id` = 364,`pt` = 'Começando em' WHERE `lang`.`id` = 364;
UPDATE `lang` SET `id` = 365,`pt` = 'Prêmio: <span class = "prêmio"> 1 BTC </ span>' WHERE `lang`.`id` = 365;
UPDATE `lang` SET `id` = 366,`pt` = 'Links quebrados:' WHERE `lang`.`id` = 366;
UPDATE `lang` SET `id` = 367,`pt` = 'Funcionalidade' WHERE `lang`.`id` = 367;
UPDATE `lang` SET `id` = 368,`pt` = 'Explorações de segurança:' WHERE `lang`.`id` = 368;
UPDATE `lang` SET `id` = 369,`pt` = 'Tempo restante' WHERE `lang`.`id` = 369;
UPDATE `lang` SET `id` = 370,`pt` = 'Acabado' WHERE `lang`.`id` = 370;
UPDATE `lang` SET `id` = 371,`pt` = 'Competição de Negociação <strong> Status </ strong>' WHERE `lang`.`id` = 371;
UPDATE `lang` SET `id` = 372,`pt` = 'Top 10 Usuários' WHERE `lang`.`id` = 372;
UPDATE `lang` SET `id` = 373,`pt` = 'USD Lucro' WHERE `lang`.`id` = 373;
UPDATE `lang` SET `id` = 374,`pt` = 'Recompensas' WHERE `lang`.`id` = 374;
UPDATE `lang` SET `id` = 375,`pt` = 'Meu Rank' WHERE `lang`.`id` = 375;
UPDATE `lang` SET `id` = 376,`pt` = 'A competição ainda não começou. Volte mais tarde!' WHERE `lang`.`id` = 376;
UPDATE `lang` SET `id` = 377,`pt` = 'Estado da Competição de Negociação' WHERE `lang`.`id` = 377;
UPDATE `lang` SET `id` = 378,`pt` = 'Este recurso está desativado até o término de nossa <a href="contest-status.php"> concorrência comercial </a>.' WHERE `lang`.`id` = 378;
UPDATE `lang` SET `id` = 379,`pt` = 'Esta funcionalidade está desativada até ao início da nossa <a href="contest-status.php"> concorrência comercial </a>.' WHERE `lang`.`id` = 379;
UPDATE `lang` SET `id` = 380,`pt` = 'Simulação' WHERE `lang`.`id` = 380;
UPDATE `lang` SET `id` = 381,`pt` = 'Ver estado da concorrência.' WHERE `lang`.`id` = 381;
UPDATE `lang` SET `id` = 382,`pt` = 'Ver regras de competição' WHERE `lang`.`id` = 382;
UPDATE `lang` SET `id` = 383,`pt` = 'Primeiro lugar' WHERE `lang`.`id` = 383;
UPDATE `lang` SET `id` = 384,`pt` = 'Segundo lugar' WHERE `lang`.`id` = 384;
UPDATE `lang` SET `id` = 385,`pt` = 'Terceiro lugar' WHERE `lang`.`id` = 385;
UPDATE `lang` SET `id` = 386,`pt` = 'Patrocinado por' WHERE `lang`.`id` = 386;
UPDATE `lang` SET `id` = 387,`pt` = 'Página não encontrada' WHERE `lang`.`id` = 387;
UPDATE `lang` SET `id` = 388,`pt` = 'A página que você está procurando não pôde ser encontrada.' WHERE `lang`.`id` = 388;
UPDATE `lang` SET `id` = 389,`pt` = 'Voltar para casa' WHERE `lang`.`id` = 389;
UPDATE `lang` SET `id` = 390,`pt` = 'Junte-se ao nosso Desafio de Negociação!' WHERE `lang`.`id` = 390;
UPDATE `lang` SET `id` = 391,`pt` = 'Nosso Desafio de Negociação Começou!' WHERE `lang`.`id` = 391;
UPDATE `lang` SET `id` = 392,`pt` = 'Estamos dando <strong> <i class = "fa fa-btc"> </ i> 10 </ strong> em dinheiro e prêmios!' WHERE `lang`.`id` = 392;
UPDATE `lang` SET `id` = 393,`pt` = 'Começou!' WHERE `lang`.`id` = 393;
UPDATE `lang` SET `id` = 394,`pt` = '4º-10º' WHERE `lang`.`id` = 394;
UPDATE `lang` SET `id` = 395,`pt` = '<a href="http://bitcointrezor.com"> Trezor </a> carteira de hardware para corredores até 4º-10º.' WHERE `lang`.`id` = 395;
UPDATE `lang` SET `id` = 396,`pt` = 'De <b> 9 </ b> a <b> 19 </ b> de Setembro' WHERE `lang`.`id` = 396;
UPDATE `lang` SET `id` = 398,`pt` = 'Troca [currency] para <strong> [c_currency] </ strong>' WHERE `lang`.`id` = 398;
UPDATE `lang` SET `id` = 399,`pt` = '[currency] para <strong> [c_currency] </ strong> preços históricos e livro de encomendas.' WHERE `lang`.`id` = 399;
UPDATE `lang` SET `id` = 400,`pt` = 'Inscreva-se no Exchange [currency] para [c_currency]' WHERE `lang`.`id` = 400;
UPDATE `lang` SET `id` = 401,`pt` = 'Alguns dos caracteres da sua senha não são permitidos ([characters]).' WHERE `lang`.`id` = 401;
UPDATE `lang` SET `id` = 402,`pt` = 'API' WHERE `lang`.`id` = 402;
UPDATE `lang` SET `id` = 403,`pt` = 'Sua chave de API foi gerada com êxito.' WHERE `lang`.`id` = 403;
UPDATE `lang` SET `id` = 404,`pt` = 'Seu <b> segredo da API </ b> é: <br/> <span class = "larger"> [secret] </ span> <br/> Por favor, dê a esse valor para baixo, pois não poderá ser recuperado mais tarde!' WHERE `lang`.`id` = 404;
UPDATE `lang` SET `id` = 405,`pt` = 'Suas permissões de API foram editadas com êxito.' WHERE `lang`.`id` = 405;
UPDATE `lang` SET `id` = 406,`pt` = 'A chave da API selecionada foi excluída.' WHERE `lang`.`id` = 406;
UPDATE `lang` SET `id` = 407,`pt` = 'A chave de API selecionada não pôde ser excluída.' WHERE `lang`.`id` = 407;
UPDATE `lang` SET `id` = 408,`pt` = 'Configuração de chaves de API' WHERE `lang`.`id` = 408;
UPDATE `lang` SET `id` = 409,`pt` = 'Configuração da API desativada' WHERE `lang`.`id` = 409;
UPDATE `lang` SET `id` = 410,`pt` = 'Você deve ativar o 2FA em sua conta para continuar.' WHERE `lang`.`id` = 410;
UPDATE `lang` SET `id` = 411,`pt` = 'Configuração de 2FA' WHERE `lang`.`id` = 411;
UPDATE `lang` SET `id` = 412,`pt` = 'Gerar nova chave' WHERE `lang`.`id` = 412;
UPDATE `lang` SET `id` = 413,`pt` = 'Salvar permissões de API' WHERE `lang`.`id` = 413;
UPDATE `lang` SET `id` = 414,`pt` = 'Chaves API disponíveis' WHERE `lang`.`id` = 414;
UPDATE `lang` SET `id` = 415,`pt` = 'Chave da API' WHERE `lang`.`id` = 415;
UPDATE `lang` SET `id` = 416,`pt` = 'Permissões' WHERE `lang`.`id` = 416;
UPDATE `lang` SET `id` = 417,`pt` = 'Ver informações da conta.' WHERE `lang`.`id` = 417;
UPDATE `lang` SET `id` = 418,`pt` = 'Criar / editar ordens' WHERE `lang`.`id` = 418;
UPDATE `lang` SET `id` = 419,`pt` = 'Retirar fundos' WHERE `lang`.`id` = 419;
UPDATE `lang` SET `id` = 420,`pt` = 'Não há chaves de API para mostrar.' WHERE `lang`.`id` = 420;
UPDATE `lang` SET `id` = 422,`pt` = 'Pré-registro' WHERE `lang`.`id` = 422;
UPDATE `lang` SET `id` = 423,`pt` = 'Pré-registo' WHERE `lang`.`id` = 423;
UPDATE `lang` SET `id` = 424,`pt` = 'Cadastre-se agora e comece a negociar o Bitcoin em 30 moedas diferentes!' WHERE `lang`.`id` = 424;
UPDATE `lang` SET `id` = 425,`pt` = 'Conta aberta' WHERE `lang`.`id` = 425;
UPDATE `lang` SET `id` = 426,`pt` = 'Tempo restante' WHERE `lang`.`id` = 426;
UPDATE `lang` SET `id` = 427,`pt` = 'Este recurso é desativado até o início das operações.' WHERE `lang`.`id` = 427;
UPDATE `lang` SET `id` = 428,`pt` = 'Ver no GitHub' WHERE `lang`.`id` = 428;
UPDATE `lang` SET `id` = 429,`pt` = 'parou' WHERE `lang`.`id` = 429;
UPDATE `lang` SET `id` = 430,`pt` = 'A negociação foi suspensa temporariamente para fins de manutenção. Ele será retomado em breve.' WHERE `lang`.`id` = 430;
UPDATE `lang` SET `id` = 431,`pt` = 'As retiradas são suspensas temporariamente para fins de manutenção. Eles vão funcionar novamente em breve.' WHERE `lang`.`id` = 431;
UPDATE `lang` SET `id` = 432,`pt` = 'A última transação ocorreu na moeda dentro dos parênteses' WHERE `lang`.`id` = 432;
UPDATE `lang` SET `id` = 433,`pt` = 'Documentação da API' WHERE `lang`.`id` = 433;
UPDATE `lang` SET `id` = 434,`pt` = 'Acesso à API' WHERE `lang`.`id` = 434;
UPDATE `lang` SET `id` = 435,`pt` = 'Para obter documentação sobre como utilizar esta API, consulte a <u> <a href="api-docs.php"> documentação da API </a> </ u>.' WHERE `lang`.`id` = 435;
UPDATE `lang` SET `id` = 436,`pt` = 'Notificar por e-mail quando os levantamentos criptográficos são feitos.' WHERE `lang`.`id` = 436;
UPDATE `lang` SET `id` = 437,`pt` = 'Notificar por e-mail quando as retiradas para contas bancárias são feitas.' WHERE `lang`.`id` = 437;
UPDATE `lang` SET `id` = 438,`pt` = 'Taxa Blockchain' WHERE `lang`.`id` = 438;
UPDATE `lang` SET `id` = 439,`pt` = 'Taxa que a rede cobra pelas transações.' WHERE `lang`.`id` = 439;
UPDATE `lang` SET `id` = 440,`pt` = '[c_currency] para receber' WHERE `lang`.`id` = 440;
UPDATE `lang` SET `id` = 441,`pt` = '[currency] para receber' WHERE `lang`.`id` = 441;
UPDATE `lang` SET `id` = 442,`pt` = 'Valor líquido' WHERE `lang`.`id` = 442;
UPDATE `lang` SET `id` = 443,`pt` = 'Último' WHERE `lang`.`id` = 443;
UPDATE `lang` SET `id` = 444,`pt` = 'Primeiro' WHERE `lang`.`id` = 444;
UPDATE `lang` SET `id` = 448,`pt` = 'Cancelou todas as suas ordens.' WHERE `lang`.`id` = 448;
UPDATE `lang` SET `id` = 449,`pt` = 'Ocorreu um erro ao cancelar as suas ordens.' WHERE `lang`.`id` = 449;
UPDATE `lang` SET `id` = 450,`pt` = 'Cancelar todas as ordens?' WHERE `lang`.`id` = 450;
UPDATE `lang` SET `id` = 451,`pt` = 'Cancelar todas as ordens?' WHERE `lang`.`id` = 451;
UPDATE `lang` SET `id` = 455,`pt` = 'Bem-vindo à conta' WHERE `lang`.`id` = 455;
UPDATE `lang` SET `id` = 457,`pt` = 'O registro está desativado temporariamente.' WHERE `lang`.`id` = 457;
UPDATE `lang` SET `id` = 461,`pt` = '' WHERE `lang`.`id` = 461;
UPDATE `lang` SET `id` = 462,`pt` = '' WHERE `lang`.`id` = 462;
UPDATE `lang` SET `id` = 463,`pt` = '' WHERE `lang`.`id` = 463;
UPDATE `lang` SET `id` = 464,`pt` = '' WHERE `lang`.`id` = 464;
UPDATE `lang` SET `id` = 465,`pt` = '' WHERE `lang`.`id` = 465;
UPDATE `lang` SET `id` = 466,`pt` = '' WHERE `lang`.`id` = 466;
UPDATE `lang` SET `id` = 467,`pt` = '' WHERE `lang`.`id` = 467;
UPDATE `lang` SET `id` = 468,`pt` = '' WHERE `lang`.`id` = 468;
UPDATE `lang` SET `id` = 471,`pt` = '' WHERE `lang`.`id` = 471;
UPDATE `lang` SET `id` = 472,`pt` = '' WHERE `lang`.`id` = 472;
UPDATE `lang` SET `id` = 473,`pt` = '' WHERE `lang`.`id` = 473;
UPDATE `lang` SET `id` = 474,`pt` = '' WHERE `lang`.`id` = 474;
UPDATE `lang` SET `id` = 475,`pt` = '' WHERE `lang`.`id` = 475;
UPDATE `lang` SET `id` = 476,`pt` = '' WHERE `lang`.`id` = 476;
UPDATE `lang` SET `id` = 477,`pt` = 'Clique para adicionar preço para vender o ticket de compra.' WHERE `lang`.`id` = 477;
UPDATE `lang` SET `id` = 478,`pt` = 'Clique para adicionar o montante para vender o pedido.' WHERE `lang`.`id` = 478;
UPDATE `lang` SET `id` = 479,`pt` = 'Clique para adicionar preço para comprar o ticket de compra.' WHERE `lang`.`id` = 479;
UPDATE `lang` SET `id` = 480,`pt` = 'Clique para adicionar o valor para comprar o ticket de pedido.' WHERE `lang`.`id` = 480;
UPDATE `lang` SET `id` = 481,`pt` = 'Chat' WHERE `lang`.`id` = 481;
UPDATE `lang` SET `id` = 482,`pt` = 'Faça login no bate-papo.' WHERE `lang`.`id` = 482;
UPDATE `lang` SET `id` = 483,`pt` = 'Identificador do bate-papo' WHERE `lang`.`id` = 483;
UPDATE `lang` SET `id` = 484,`pt` = '' WHERE `lang`.`id` = 484;
UPDATE `lang` SET `id` = 485,`pt` = '' WHERE `lang`.`id` = 485;
UPDATE `lang` SET `id` = 486,`pt` = '' WHERE `lang`.`id` = 486;
UPDATE `lang` SET `id` = 487,`pt` = '' WHERE `lang`.`id` = 487;
UPDATE `lang` SET `id` = 488,`pt` = '' WHERE `lang`.`id` = 488;
UPDATE `lang` SET `id` = 489,`pt` = '' WHERE `lang`.`id` = 489;
UPDATE `lang` SET `id` = 490,`pt` = '' WHERE `lang`.`id` = 490;
UPDATE `lang` SET `id` = 491,`pt` = '' WHERE `lang`.`id` = 491;
UPDATE `lang` SET `id` = 492,`pt` = '' WHERE `lang`.`id` = 492;
UPDATE `lang` SET `id` = 493,`pt` = '' WHERE `lang`.`id` = 493;
UPDATE `lang` SET `id` = 494,`pt` = '' WHERE `lang`.`id` = 494;
UPDATE `lang` SET `id` = 495,`pt` = '' WHERE `lang`.`id` = 495;
UPDATE `lang` SET `id` = 496,`pt` = '' WHERE `lang`.`id` = 496;
UPDATE `lang` SET `id` = 497,`pt` = '' WHERE `lang`.`id` = 497;
UPDATE `lang` SET `id` = 498,`pt` = '' WHERE `lang`.`id` = 498;
UPDATE `lang` SET `id` = 499,`pt` = '' WHERE `lang`.`id` = 499;
UPDATE `lang` SET `id` = 500,`pt` = '' WHERE `lang`.`id` = 500;
UPDATE `lang` SET `id` = 501,`pt` = '' WHERE `lang`.`id` = 501;
UPDATE `lang` SET `id` = 502,`pt` = '' WHERE `lang`.`id` = 502;
UPDATE `lang` SET `id` = 503,`pt` = '' WHERE `lang`.`id` = 503;
UPDATE `lang` SET `id` = 504,`pt` = '' WHERE `lang`.`id` = 504;
UPDATE `lang` SET `id` = 505,`pt` = '' WHERE `lang`.`id` = 505;
UPDATE `lang` SET `id` = 506,`pt` = '' WHERE `lang`.`id` = 506;
UPDATE `lang` SET `id` = 507,`pt` = '' WHERE `lang`.`id` = 507;
UPDATE `lang` SET `id` = 508,`pt` = '' WHERE `lang`.`id` = 508;
UPDATE `lang` SET `id` = 509,`pt` = '' WHERE `lang`.`id` = 509;
UPDATE `lang` SET `id` = 510,`pt` = '' WHERE `lang`.`id` = 510;
UPDATE `lang` SET `id` = 511,`pt` = '' WHERE `lang`.`id` = 511;
UPDATE `lang` SET `id` = 512,`pt` = 'Mercado Padrão' WHERE `lang`.`id` = 512;
UPDATE `lang` SET `id` = 513,`pt` = 'Mercado' WHERE `lang`.`id` = 513;
UPDATE `lang` SET `id` = 514,`pt` = 'A moeda padrão não pode ser igual ao mercado padrão.' WHERE `lang`.`id` = 514;
UPDATE `lang` SET `id` = 515,`pt` = 'O preço mínimo para [cripto] é [min].' WHERE `lang`.`id` = 515;
UPDATE `lang` SET `id` = 516,`pt` = 'Moeda para Depósito' WHERE `lang`.`id` = 516;
UPDATE `lang` SET `id` = 517,`pt` = 'Clique para adicionar o valor total para comprar o ticket.' WHERE `lang`.`id` = 517;
UPDATE `lang` SET `id` = 518,`pt` = 'Clique para adicionar o valor total para vender o bilhete.' WHERE `lang`.`id` = 518;
